export const MEMORY_CATEGORIES = Object.freeze([
    { value: 'mixed', label: 'All Categories' },
    { value: 'space-plants', label: 'Space Plants' },
    { value: 'aliens', label: 'Imaginary Aliens' },
    { value: 'monsters', label: 'Imaginary Monsters' },
    { value: 'plants', label: 'Real Plants' },
    { value: 'animals', label: 'Real Animals' },
    { value: 'buildings', label: 'Buildings' },
    { value: 'cars', label: 'Cars' },
    { value: 'airplanes', label: 'Airplanes' },
    { value: 'rockets', label: 'Rockets' },
    { value: 'ships', label: 'Ships' },
    { value: 'transport', label: 'Other Vehicles' },
    { value: 'objects', label: 'Everyday Objects' },
    { value: 'landscapes', label: 'Landscapes' },
    { value: 'cities', label: 'Cities' },
]);

export const MEMORY_CATALOG = Object.freeze([
    { id: 'space-nebula-bloom', name: 'Meglični cvet', category: 'space-plants', image: './assets/space-plants/nebula-bloom.webp' },
    { id: 'space-orbit-cactus', name: 'Orbitni kaktus', category: 'space-plants', image: './assets/space-plants/orbit-cactus.webp' },
    { id: 'space-moonbell', name: 'Lunin zvonček', category: 'space-plants', image: './assets/space-plants/moonbell.webp' },
    { id: 'space-plasma-fern', name: 'Plazemska praprot', category: 'space-plants', image: './assets/space-plants/plasma-fern.webp' },
    { id: 'space-comet-vine', name: 'Kometna ovijalka', category: 'space-plants', image: './assets/space-plants/comet-vine.webp' },
    { id: 'space-crystal-aloe', name: 'Kristalna aloja', category: 'space-plants', image: './assets/space-plants/crystal-aloe.webp' },
    { id: 'space-eclipse-mushroom', name: 'Mrkovka', category: 'space-plants', image: './assets/space-plants/eclipse-mushroom.webp' },
    { id: 'space-bubble-reed', name: 'Mehurjasti trst', category: 'space-plants', image: './assets/space-plants/bubble-reed.webp' },
    { id: 'space-solar-sundew', name: 'Sončna rosika', category: 'space-plants', image: './assets/space-plants/solar-sundew.webp' },
    { id: 'space-gravity-lotus', name: 'Gravitacijski lotos', category: 'space-plants', image: './assets/space-plants/gravity-lotus.webp' },
    { id: 'alien-teal-three-eyed-ambassador', name: 'Turkizni trijeoki diplomat', category: 'aliens', image: './assets/aliens/teal-three-eyed-ambassador.jpg' },
    { id: 'alien-jellyfish-sky', name: 'Lebdeči meduzasti vesoljec', category: 'aliens', image: './assets/aliens/jellyfish-sky-alien.jpg' },
    { id: 'alien-crystal-quadruped', name: 'Kristalni štirinožec', category: 'aliens', image: './assets/aliens/crystal-quadruped.jpg' },
    { id: 'alien-fuzzy-moon-explorer', name: 'Kosmati lunarni raziskovalec', category: 'aliens', image: './assets/aliens/fuzzy-moon-explorer.jpg' },
    { id: 'alien-ring-neck-botanist', name: 'Obročasti vesoljski botanik', category: 'aliens', image: './assets/aliens/ring-neck-botanist.jpg' },
    { id: 'alien-bioluminescent-cave-navigator', name: 'Bioluminiscenčni jamski vodnik', category: 'aliens', image: './assets/aliens/bioluminescent-cave-navigator.jpg' },
    { id: 'alien-copper-shell-engineer', name: 'Bakreni oklepni inženir', category: 'aliens', image: './assets/aliens/copper-shell-engineer.jpg' },
    { id: 'alien-cloud-whale', name: 'Nebesni kit', category: 'aliens', image: './assets/aliens/cloud-whale-alien.jpg' },
    { id: 'alien-striped-four-arm-musician', name: 'Črtasti štiriroki glasbenik', category: 'aliens', image: './assets/aliens/striped-four-arm-musician.jpg' },
    { id: 'alien-moss-pocket-gardener', name: 'Mahovnati žepni vrtnar', category: 'aliens', image: './assets/aliens/moss-pocket-gardener.jpg' },
    { id: 'alien-translucent-ice-oracle', name: 'Prosojni ledeni orakelj', category: 'aliens', image: './assets/aliens/translucent-ice-oracle.jpg' },
    { id: 'alien-red-winged-courier', name: 'Rdeči krilati kurir', category: 'aliens', image: './assets/aliens/red-winged-courier.jpg' },
    { id: 'alien-blue-amphibious-cartographer', name: 'Modri dvoživski kartograf', category: 'aliens', image: './assets/aliens/blue-amphibious-cartographer.jpg' },
    { id: 'alien-golden-sand-crawler', name: 'Zlati puščavski šestnožec', category: 'aliens', image: './assets/aliens/golden-sand-crawler.jpg' },
    { id: 'alien-floating-orb-scholar', name: 'Lebdeči kroglasti učenjak', category: 'aliens', image: './assets/aliens/floating-orb-scholar.jpg' },
    { id: 'alien-coral-antler', name: 'Koralnorogi vesoljec', category: 'aliens', image: './assets/aliens/coral-antler-alien.jpg' },
    { id: 'alien-silver-insect-pilot', name: 'Srebrni žuželčji pilot', category: 'aliens', image: './assets/aliens/silver-insect-pilot.jpg' },
    { id: 'alien-pastel-mushroom', name: 'Pastelni gobasti vesoljec', category: 'aliens', image: './assets/aliens/pastel-mushroom-alien.jpg' },
    { id: 'alien-lava-salamander', name: 'Lavnati salamander', category: 'aliens', image: './assets/aliens/lava-salamander-alien.jpg' },
    { id: 'alien-long-eared-desert-observer', name: 'Dolgouhi puščavski opazovalec', category: 'aliens', image: './assets/aliens/long-eared-desert-observer.jpg' },
    { id: 'monster-blue-one-eye-fuzzball', name: 'Modri enooki kosmatinec', category: 'monsters', image: './assets/monsters/blue-one-eye-fuzzball.jpg' },
    { id: 'monster-leaf-horn-forest', name: 'Gozdna pošast z listnatimi rogovi', category: 'monsters', image: './assets/monsters/leaf-horn-forest-monster.jpg' },
    { id: 'monster-brass-clockwork', name: 'Medeninasta urnomehanska pošast', category: 'monsters', image: './assets/monsters/brass-clockwork-monster.jpg' },
    { id: 'monster-swamp-bubble', name: 'Močvirski mehurček', category: 'monsters', image: './assets/monsters/swamp-bubble-monster.jpg' },
    { id: 'monster-cave-bat-goblin', name: 'Jamski netopirski škrat', category: 'monsters', image: './assets/monsters/cave-bat-goblin.jpg' },
    { id: 'monster-candy-striped-sock', name: 'Progasta nogavičasta pošast', category: 'monsters', image: './assets/monsters/candy-striped-sock-monster.jpg' },
    { id: 'monster-baby-stone-golem', name: 'Mali kamniti golem', category: 'monsters', image: './assets/monsters/baby-stone-golem.jpg' },
    { id: 'monster-shadow-lantern', name: 'Senčna svetilka', category: 'monsters', image: './assets/monsters/shadow-lantern-monster.jpg' },
    { id: 'monster-snowball-tusk', name: 'Snežna oklačica', category: 'monsters', image: './assets/monsters/snowball-tusk-monster.jpg' },
    { id: 'monster-pumpkin-vine', name: 'Bučna ovijalka', category: 'monsters', image: './assets/monsters/pumpkin-vine-monster.jpg' },
    { id: 'monster-octopus-librarian', name: 'Hobotnični knjižničar', category: 'monsters', image: './assets/monsters/octopus-librarian-monster.jpg' },
    { id: 'monster-three-head-cloud', name: 'Troglavi oblak', category: 'monsters', image: './assets/monsters/three-head-cloud-monster.jpg' },
    { id: 'monster-mirror-scale-serpent', name: 'Zrcalnoluskasti kačon', category: 'monsters', image: './assets/monsters/mirror-scale-serpent.jpg' },
    { id: 'monster-pancake-rug', name: 'Preprožna palačinka', category: 'monsters', image: './assets/monsters/pancake-rug-monster.jpg' },
    { id: 'monster-thunder-drum-beast', name: 'Gromovni bobnar', category: 'monsters', image: './assets/monsters/thunder-drum-beast.jpg' },
    { id: 'monster-amethyst-crab', name: 'Ametistna rakovica', category: 'monsters', image: './assets/monsters/amethyst-crab-monster.jpg' },
    { id: 'monster-giant-firefly', name: 'Velikanska kresnica', category: 'monsters', image: './assets/monsters/giant-firefly-monster.jpg' },
    { id: 'monster-tower-shell-snail', name: 'Polž s stolpastim oklepom', category: 'monsters', image: './assets/monsters/tower-shell-snail.jpg' },
    { id: 'monster-origami-paper', name: 'Origami pošast', category: 'monsters', image: './assets/monsters/origami-paper-monster.jpg' },
    { id: 'monster-deep-sea-angler', name: 'Globokomorski svetleči zobatec', category: 'monsters', image: './assets/monsters/deep-sea-angler-monster.jpg' },
    { id: 'plant-common-sunflower', name: 'Sončnica', category: 'plants', image: './assets/plants/common-sunflower.jpg' },
    { id: 'plant-english-lavender', name: 'Sivka', category: 'plants', image: './assets/plants/english-lavender.jpg' },
    { id: 'plant-monstera-deliciosa', name: 'Monstera', category: 'plants', image: './assets/plants/monstera-deliciosa.jpg' },
    { id: 'plant-saguaro-cactus', name: 'Saguaro', category: 'plants', image: './assets/plants/saguaro-cactus.jpg' },
    { id: 'plant-japanese-maple-bonsai', name: 'Bonsaj japonskega javorja', category: 'plants', image: './assets/plants/japanese-maple-bonsai.jpg' },
    { id: 'plant-red-garden-tulip', name: 'Rdeči tulipan', category: 'plants', image: './assets/plants/red-garden-tulip.jpg' },
    { id: 'plant-western-sword-fern', name: 'Mečasta praprot', category: 'plants', image: './assets/plants/western-sword-fern.jpg' },
    { id: 'plant-white-moth-orchid', name: 'Bela orhideja', category: 'plants', image: './assets/plants/white-moth-orchid.jpg' },
    { id: 'plant-white-water-lily', name: 'Beli lokvanj', category: 'plants', image: './assets/plants/white-water-lily.jpg' },
    { id: 'plant-aloe-vera', name: 'Aloe vera', category: 'plants', image: './assets/plants/aloe-vera.jpg' },
    { id: 'plant-rosemary-shrub', name: 'Rožmarin', category: 'plants', image: './assets/plants/rosemary-shrub.jpg' },
    { id: 'plant-common-dandelion', name: 'Navadni regrat', category: 'plants', image: './assets/plants/common-dandelion.jpg' },
    { id: 'plant-red-corn-poppy', name: 'Rdeči mak', category: 'plants', image: './assets/plants/red-corn-poppy.jpg' },
    { id: 'plant-english-oak-sapling', name: 'Mlad hrast', category: 'plants', image: './assets/plants/english-oak-sapling.jpg' },
    { id: 'plant-green-bamboo-cluster', name: 'Bambus', category: 'plants', image: './assets/plants/green-bamboo-cluster.jpg' },
    { id: 'plant-blue-cornflower', name: 'Modri glavinec', category: 'plants', image: './assets/plants/blue-cornflower.jpg' },
    { id: 'plant-strawberry', name: 'Jagodnjak', category: 'plants', image: './assets/plants/strawberry-plant.jpg' },
    { id: 'plant-venus-flytrap', name: 'Venerina muholovka', category: 'plants', image: './assets/plants/venus-flytrap.jpg' },
    { id: 'plant-edelweiss', name: 'Planika', category: 'plants', image: './assets/plants/edelweiss.jpg' },
    { id: 'plant-young-olive-tree', name: 'Mlada oljka', category: 'plants', image: './assets/plants/young-olive-tree.jpg' },
    { id: 'animal-red-fox', name: 'Rdeča lisica', category: 'animals', image: './assets/animals/red-fox.jpg' },
    { id: 'animal-african-elephant', name: 'Afriški slon', category: 'animals', image: './assets/animals/african-elephant.jpg' },
    { id: 'animal-emperor-penguin', name: 'Cesarski pingvin', category: 'animals', image: './assets/animals/emperor-penguin.jpg' },
    { id: 'animal-green-tree-frog', name: 'Zelena drevesna žaba', category: 'animals', image: './assets/animals/green-tree-frog.jpg' },
    { id: 'animal-barn-owl', name: 'Pegasta sova', category: 'animals', image: './assets/animals/barn-owl.jpg' },
    { id: 'animal-bottlenose-dolphin', name: 'Velika pliskavka', category: 'animals', image: './assets/animals/bottlenose-dolphin.jpg' },
    { id: 'animal-bengal-tiger', name: 'Bengalski tiger', category: 'animals', image: './assets/animals/bengal-tiger.jpg' },
    { id: 'animal-european-hedgehog', name: 'Evropski jež', category: 'animals', image: './assets/animals/european-hedgehog.jpg' },
    { id: 'animal-blue-yellow-macaw', name: 'Modro-rumena ara', category: 'animals', image: './assets/animals/blue-yellow-macaw.jpg' },
    { id: 'animal-giant-panda', name: 'Veliki panda', category: 'animals', image: './assets/animals/giant-panda.jpg' },
    { id: 'animal-common-octopus', name: 'Navadna hobotnica', category: 'animals', image: './assets/animals/common-octopus.jpg' },
    { id: 'animal-plains-zebra', name: 'Stepska zebra', category: 'animals', image: './assets/animals/plains-zebra.jpg' },
    { id: 'animal-red-squirrel', name: 'Navadna veverica', category: 'animals', image: './assets/animals/red-squirrel.jpg' },
    { id: 'animal-green-sea-turtle', name: 'Zelena morska želva', category: 'animals', image: './assets/animals/green-sea-turtle.jpg' },
    { id: 'animal-alpine-ibex', name: 'Alpski kozorog', category: 'animals', image: './assets/animals/alpine-ibex.jpg' },
    { id: 'animal-monarch-butterfly', name: 'Metulj monarh', category: 'animals', image: './assets/animals/monarch-butterfly.jpg' },
    { id: 'animal-brown-bear', name: 'Rjavi medved', category: 'animals', image: './assets/animals/brown-bear.jpg' },
    { id: 'animal-meerkat', name: 'Surikata', category: 'animals', image: './assets/animals/meerkat.jpg' },
    { id: 'animal-seahorse', name: 'Morski konjiček', category: 'animals', image: './assets/animals/seahorse.jpg' },
    { id: 'animal-ring-tailed-lemur', name: 'Obročkastorepi maki', category: 'animals', image: './assets/animals/ring-tailed-lemur.jpg' },
    { id: 'building-slovenian-alpine-farmhouse', name: 'Slovenska alpska domačija', category: 'buildings', image: './assets/buildings/slovenian-alpine-farmhouse.jpg' },
    { id: 'building-medieval-stone-castle', name: 'Srednjeveški grad', category: 'buildings', image: './assets/buildings/medieval-stone-castle.jpg' },
    { id: 'building-modern-glass-skyscraper', name: 'Stekleni nebotičnik', category: 'buildings', image: './assets/buildings/modern-glass-skyscraper.jpg' },
    { id: 'building-greek-island-house', name: 'Grška otoška hiša', category: 'buildings', image: './assets/buildings/greek-island-house.jpg' },
    { id: 'building-red-brick-gothic-cathedral', name: 'Gotska katedrala', category: 'buildings', image: './assets/buildings/red-brick-gothic-cathedral.jpg' },
    { id: 'building-japanese-pagoda', name: 'Japonska pagoda', category: 'buildings', image: './assets/buildings/japanese-pagoda.jpg' },
    { id: 'building-roman-amphitheatre', name: 'Rimski amfiteater', category: 'buildings', image: './assets/buildings/roman-amphitheatre.jpg' },
    { id: 'building-art-nouveau-townhouse', name: 'Secesijska meščanska hiša', category: 'buildings', image: './assets/buildings/art-nouveau-townhouse.jpg' },
    { id: 'building-desert-adobe-pueblo', name: 'Puščanska hiša pueblo', category: 'buildings', image: './assets/buildings/desert-adobe-pueblo.jpg' },
    { id: 'building-scandinavian-cabin', name: 'Skandinavska koča', category: 'buildings', image: './assets/buildings/scandinavian-cabin.jpg' },
    { id: 'building-neoclassical-museum', name: 'Neoklasicistični muzej', category: 'buildings', image: './assets/buildings/neoclassical-museum.jpg' },
    { id: 'building-futuristic-geodesic-dome', name: 'Geodetska raziskovalna kupola', category: 'buildings', image: './assets/buildings/futuristic-geodesic-dome.jpg' },
    { id: 'building-dutch-windmill', name: 'Nizozemski mlin na veter', category: 'buildings', image: './assets/buildings/dutch-windmill.jpg' },
    { id: 'building-victorian-row-house', name: 'Viktorijanska hiša', category: 'buildings', image: './assets/buildings/victorian-row-house.jpg' },
    { id: 'building-brutalist-civic-building', name: 'Brutalistična javna stavba', category: 'buildings', image: './assets/buildings/brutalist-civic-building.jpg' },
    { id: 'building-tropical-stilt-house', name: 'Tropska hiša na kolih', category: 'buildings', image: './assets/buildings/tropical-stilt-house.jpg' },
    { id: 'building-chinese-gatehouse', name: 'Kitajska dvoriščna vrata', category: 'buildings', image: './assets/buildings/chinese-gatehouse.jpg' },
    { id: 'building-lighthouse', name: 'Svetilnik', category: 'buildings', image: './assets/buildings/lighthouse.jpg' },
    { id: 'building-stone-chapel', name: 'Kamnita kapelica', category: 'buildings', image: './assets/buildings/stone-chapel.jpg' },
    { id: 'building-sustainable-house', name: 'Trajnostna hiša', category: 'buildings', image: './assets/buildings/sustainable-house.jpg' },
    { id: 'car-red-vintage-beetle', name: 'Rdeči hrošč', category: 'cars', image: './assets/cars/red-vintage-beetle.jpg' },
    { id: 'car-blue-sports-coupe', name: 'Modri športni kupe', category: 'cars', image: './assets/cars/blue-sports-coupe.jpg' },
    { id: 'car-yellow-classic-taxi', name: 'Rumeni taksi', category: 'cars', image: './assets/cars/yellow-classic-taxi.jpg' },
    { id: 'car-green-offroad-jeep', name: 'Zeleni terenec', category: 'cars', image: './assets/cars/green-offroad-jeep.jpg' },
    { id: 'car-white-electric-sedan', name: 'Bela električna limuzina', category: 'cars', image: './assets/cars/white-electric-sedan.jpg' },
    { id: 'car-orange-rally', name: 'Oranžni reli avto', category: 'cars', image: './assets/cars/orange-rally-car.jpg' },
    { id: 'car-silver-convertible', name: 'Srebrni kabriolet', category: 'cars', image: './assets/cars/silver-convertible.jpg' },
    { id: 'car-pastel-microcar', name: 'Pastelni mikroavto', category: 'cars', image: './assets/cars/pastel-microcar.jpg' },
    { id: 'car-black-1960s-muscle', name: 'Črni ameriški mišičnjak', category: 'cars', image: './assets/cars/black-1960s-muscle-car.jpg' },
    { id: 'car-turquoise-camper-van', name: 'Turkizni avtodom', category: 'cars', image: './assets/cars/turquoise-camper-van.jpg' },
    { id: 'car-purple-city-hatchback', name: 'Vijolični mestni avtomobil', category: 'cars', image: './assets/cars/purple-city-hatchback.jpg' },
    { id: 'car-blue-family-station-wagon', name: 'Modri družinski karavan', category: 'cars', image: './assets/cars/blue-family-station-wagon.jpg' },
    { id: 'car-red-modern-pickup', name: 'Rdeči poltovornjak', category: 'cars', image: './assets/cars/red-modern-pickup.jpg' },
    { id: 'car-cream-1950s-luxury-sedan', name: 'Kremna limuzina iz petdesetih', category: 'cars', image: './assets/cars/cream-1950s-luxury-sedan.jpg' },
    { id: 'car-lime-futuristic-concept', name: 'Zeleni futuristični koncept', category: 'cars', image: './assets/cars/lime-futuristic-concept-car.jpg' },
    { id: 'car-yellow-compact-delivery-van', name: 'Rumeni dostavni kombi', category: 'cars', image: './assets/cars/yellow-compact-delivery-van.jpg' },
    { id: 'car-burgundy-grand-touring-coupe', name: 'Bordo potovalni kupe', category: 'cars', image: './assets/cars/burgundy-grand-touring-coupe.jpg' },
    { id: 'car-sky-blue-small-roadster', name: 'Svetlomodri roadster', category: 'cars', image: './assets/cars/sky-blue-small-roadster.jpg' },
    { id: 'car-forest-green-modern-minivan', name: 'Temnozeleni enoprostorec', category: 'cars', image: './assets/cars/forest-green-modern-minivan.jpg' },
    { id: 'car-copper-electric-crossover', name: 'Bakreni električni križanec', category: 'cars', image: './assets/cars/copper-electric-crossover.jpg' },
    { id: 'airplane-blue-white-passenger-jet', name: 'Modro-belo potniško letalo', category: 'airplanes', image: './assets/airplanes/blue-white-passenger-jet.jpg' },
    { id: 'airplane-red-vintage-biplane', name: 'Rdeči dvokrilec', category: 'airplanes', image: './assets/airplanes/red-vintage-biplane.jpg' },
    { id: 'airplane-white-alpine-glider', name: 'Belo jadralno letalo', category: 'airplanes', image: './assets/airplanes/white-alpine-glider.jpg' },
    { id: 'airplane-yellow-bush-plane', name: 'Rumeno terensko letalo', category: 'airplanes', image: './assets/airplanes/yellow-bush-plane.jpg' },
    { id: 'airplane-turquoise-seaplane', name: 'Turkizni hidroplan', category: 'airplanes', image: './assets/airplanes/turquoise-seaplane.jpg' },
    { id: 'airplane-silver-four-engine-airliner', name: 'Srebrno štirimotorno potniško letalo', category: 'airplanes', image: './assets/airplanes/silver-four-engine-airliner.jpg' },
    { id: 'airplane-orange-aerobatic', name: 'Oranžno akrobatsko letalo', category: 'airplanes', image: './assets/airplanes/orange-aerobatic-plane.jpg' },
    { id: 'airplane-white-business-jet', name: 'Belo poslovno letalo', category: 'airplanes', image: './assets/airplanes/white-business-jet.jpg' },
    { id: 'airplane-green-crop-duster', name: 'Zeleno škropilno letalo', category: 'airplanes', image: './assets/airplanes/green-crop-duster.jpg' },
    { id: 'airplane-cream-pioneer-monoplane', name: 'Kremno pionirsko letalo', category: 'airplanes', image: './assets/airplanes/cream-pioneer-monoplane.jpg' },
    { id: 'airplane-blue-high-wing-trainer', name: 'Modro šolsko letalo', category: 'airplanes', image: './assets/airplanes/blue-high-wing-trainer.jpg' },
    { id: 'airplane-red-white-rescue-flying-boat', name: 'Rdeče-beli leteči čoln', category: 'airplanes', image: './assets/airplanes/red-white-rescue-flying-boat.jpg' },
    { id: 'airplane-silver-supersonic-airliner', name: 'Srebrno nadzvočno letalo', category: 'airplanes', image: './assets/airplanes/silver-supersonic-airliner.jpg' },
    { id: 'airplane-yellow-autogyro', name: 'Rumeni žiroplan', category: 'airplanes', image: './assets/airplanes/yellow-autogyro.jpg' },
    { id: 'airplane-white-solar-experimental', name: 'Belo sončno letalo', category: 'airplanes', image: './assets/airplanes/white-solar-experimental-plane.jpg' },
    { id: 'airplane-purple-amphibious-light', name: 'Vijolično amfibijsko letalo', category: 'airplanes', image: './assets/airplanes/purple-amphibious-light-plane.jpg' },
    { id: 'airplane-orange-twin-boom-utility', name: 'Oranžno dvotrupno letalo', category: 'airplanes', image: './assets/airplanes/orange-twin-boom-utility-plane.jpg' },
    { id: 'airplane-white-cargo-turboprop', name: 'Belo tovorno turbopropelersko letalo', category: 'airplanes', image: './assets/airplanes/white-cargo-turboprop.jpg' },
    { id: 'airplane-dark-teal-canard', name: 'Temnoturkizno racasto letalo', category: 'airplanes', image: './assets/airplanes/dark-teal-canard-plane.jpg' },
    { id: 'airplane-red-vintage-racing', name: 'Rdeče starodobno dirkalno letalo', category: 'airplanes', image: './assets/airplanes/red-vintage-racing-plane.jpg' },
    { id: 'rocket-three-stage-moon', name: 'Tristopenjska lunarna raketa', category: 'rockets', image: './assets/rockets/three-stage-moon-rocket.jpg' },
    { id: 'rocket-reusable-winged-spaceplane', name: 'Ponovno uporabni raketoplan', category: 'rockets', image: './assets/rockets/reusable-winged-spaceplane.jpg' },
    { id: 'rocket-orange-white-sounding', name: 'Oranžno-bela raziskovalna raketa', category: 'rockets', image: './assets/rockets/orange-white-sounding-rocket.jpg' },
    { id: 'rocket-silver-crew-capsule', name: 'Srebrna vesoljska kapsula', category: 'rockets', image: './assets/rockets/silver-crew-capsule.jpg' },
    { id: 'rocket-gold-foil-lunar-lander', name: 'Zlati lunarni pristajalnik', category: 'rockets', image: './assets/rockets/gold-foil-lunar-lander.jpg' },
    { id: 'rocket-white-orange-side-boosters', name: 'Bela raketa z oranžnima pospeševalnikoma', category: 'rockets', image: './assets/rockets/white-rocket-orange-side-boosters.jpg' },
    { id: 'rocket-blue-reusable-stage', name: 'Modra povratna raketna stopnja', category: 'rockets', image: './assets/rockets/blue-reusable-rocket-stage.jpg' },
    { id: 'rocket-copper-mars-probe', name: 'Bakrena marsovska sonda', category: 'rockets', image: './assets/rockets/copper-mars-probe.jpg' },
    { id: 'rocket-silver-cube-satellite', name: 'Srebrni kockasti satelit', category: 'rockets', image: './assets/rockets/silver-cube-satellite.jpg' },
    { id: 'rocket-white-gold-space-telescope', name: 'Belo-zlati vesoljski teleskop', category: 'rockets', image: './assets/rockets/white-gold-space-telescope.jpg' },
    { id: 'rocket-green-white-four-booster', name: 'Zeleno-bela raketa s štirimi pospeševalniki', category: 'rockets', image: './assets/rockets/green-white-four-booster-rocket.jpg' },
    { id: 'rocket-red-retro-moon', name: 'Rdeča retro raketa', category: 'rockets', image: './assets/rockets/red-retro-moon-rocket.jpg' },
    { id: 'rocket-white-orbital-transfer-tug', name: 'Beli orbitalni vlačilec', category: 'rockets', image: './assets/rockets/white-orbital-transfer-tug.jpg' },
    { id: 'rocket-orange-mars-rover', name: 'Oranžni marsovski rover', category: 'rockets', image: './assets/rockets/orange-mars-rover.jpg' },
    { id: 'rocket-silver-asteroid-sample-return', name: 'Srebrna sonda za vzorce asteroidov', category: 'rockets', image: './assets/rockets/silver-asteroid-sample-return.jpg' },
    { id: 'rocket-yellow-white-small-launcher', name: 'Rumeno-bela mala nosilna raketa', category: 'rockets', image: './assets/rockets/yellow-white-small-launcher.jpg' },
    { id: 'rocket-black-silver-parachute-capsule', name: 'Črno-srebrna povratna kapsula', category: 'rockets', image: './assets/rockets/black-silver-parachute-capsule.jpg' },
    { id: 'rocket-white-venus-balloon-probe', name: 'Bela balonska sonda za Venero', category: 'rockets', image: './assets/rockets/white-venus-balloon-probe.jpg' },
    { id: 'rocket-blue-ice-moon-cryobot', name: 'Modri kriobot', category: 'rockets', image: './assets/rockets/blue-ice-moon-cryobot.jpg' },
    { id: 'rocket-silver-solar-sail-probe', name: 'Srebrna sonda s sončnim jadrom', category: 'rockets', image: './assets/rockets/silver-solar-sail-probe.jpg' },
    { id: 'ship-white-blue-sailing-yacht', name: 'Bela jadrnica z modrim jadrom', category: 'ships', image: './assets/ships/white-blue-sailing-yacht.jpg' },
    { id: 'ship-red-black-harbor-tugboat', name: 'Rdeče-črni pristaniški vlačilec', category: 'ships', image: './assets/ships/red-black-harbor-tugboat.jpg' },
    { id: 'ship-blue-container', name: 'Modra kontejnerska ladja', category: 'ships', image: './assets/ships/blue-container-ship.jpg' },
    { id: 'ship-green-fishing-trawler', name: 'Zelena ribiška ladja', category: 'ships', image: './assets/ships/green-fishing-trawler.jpg' },
    { id: 'ship-white-yellow-passenger-ferry', name: 'Belo-rumeni trajekt', category: 'ships', image: './assets/ships/white-yellow-passenger-ferry.jpg' },
    { id: 'ship-red-offshore-rescue-lifeboat', name: 'Rdeči reševalni čoln', category: 'ships', image: './assets/ships/red-offshore-rescue-lifeboat.jpg' },
    { id: 'ship-cream-river-paddle-steamer', name: 'Kremni rečni parnik', category: 'ships', image: './assets/ships/cream-river-paddle-steamer.jpg' },
    { id: 'ship-white-turquoise-sailing-catamaran', name: 'Belo-turkizni jadralni katamaran', category: 'ships', image: './assets/ships/white-turquoise-sailing-catamaran.jpg' },
    { id: 'ship-dark-blue-research', name: 'Temnomodra raziskovalna ladja', category: 'ships', image: './assets/ships/dark-blue-research-ship.jpg' },
    { id: 'ship-black-white-polar-icebreaker', name: 'Črno-beli ledolomilec', category: 'ships', image: './assets/ships/black-white-polar-icebreaker.jpg' },
    { id: 'ship-brown-wooden-water-taxi', name: 'Rjavi leseni vodni taksi', category: 'ships', image: './assets/ships/brown-wooden-water-taxi.jpg' },
    { id: 'ship-yellow-recreational-submarine', name: 'Rumena turistična podmornica', category: 'ships', image: './assets/ships/yellow-recreational-submarine.jpg' },
    { id: 'ship-white-modern-cruise', name: 'Bela sodobna potniška ladja', category: 'ships', image: './assets/ships/white-modern-cruise-ship.jpg' },
    { id: 'ship-brown-viking-longship', name: 'Rjava vikinška dolga ladja', category: 'ships', image: './assets/ships/brown-viking-longship.jpg' },
    { id: 'ship-orange-pilot-boat', name: 'Oranžni pilotski čoln', category: 'ships', image: './assets/ships/orange-pilot-boat.jpg' },
    { id: 'ship-green-dragon-boat', name: 'Zeleni zmajski čoln', category: 'ships', image: './assets/ships/green-dragon-boat.jpg' },
    { id: 'ship-white-passenger-hydrofoil', name: 'Beli potniški hidrogliser', category: 'ships', image: './assets/ships/white-passenger-hydrofoil.jpg' },
    { id: 'ship-blue-white-roro-ferry', name: 'Modro-beli tovorni trajekt', category: 'ships', image: './assets/ships/blue-white-roro-ferry.jpg' },
    { id: 'ship-cream-red-canal-narrowboat', name: 'Kremni kanalski čoln', category: 'ships', image: './assets/ships/cream-red-canal-narrowboat.jpg' },
    { id: 'ship-mahogany-classic-speedboat', name: 'Mahagonijev klasični gliser', category: 'ships', image: './assets/ships/mahogany-classic-speedboat.jpg' },
    { id: 'transport-red-modern-city-tram', name: 'Rdeči mestni tramvaj', category: 'transport', image: './assets/transport/red-modern-city-tram.jpg' },
    { id: 'transport-blue-electric-commuter-train', name: 'Modri električni vlak', category: 'transport', image: './assets/transport/blue-electric-commuter-train.jpg' },
    { id: 'transport-yellow-articulated-city-bus', name: 'Rumeni zgibni avtobus', category: 'transport', image: './assets/transport/yellow-articulated-city-bus.jpg' },
    { id: 'transport-mint-green-classic-bicycle', name: 'Mintno zeleno mestno kolo', category: 'transport', image: './assets/transport/mint-green-classic-bicycle.jpg' },
    { id: 'transport-orange-touring-motorcycle', name: 'Oranžni potovalni motor', category: 'transport', image: './assets/transport/orange-touring-motorcycle.jpg' },
    { id: 'transport-cream-red-vintage-cable-car', name: 'Kremno-rdeča vzpenjača', category: 'transport', image: './assets/transport/cream-red-vintage-cable-car.jpg' },
    { id: 'transport-dark-green-steam-locomotive', name: 'Temnozelena parna lokomotiva', category: 'transport', image: './assets/transport/dark-green-steam-locomotive.jpg' },
    { id: 'transport-bright-blue-kick-scooter', name: 'Moder skiro', category: 'transport', image: './assets/transport/bright-blue-kick-scooter.jpg' },
    { id: 'transport-brown-horse-drawn-carriage', name: 'Rjava kočija', category: 'transport', image: './assets/transport/brown-horse-drawn-carriage.jpg' },
    { id: 'transport-colorful-hot-air-balloon', name: 'Pisani toplozračni balon', category: 'transport', image: './assets/transport/colorful-hot-air-balloon.jpg' },
    { id: 'transport-white-blue-elevated-monorail', name: 'Belo-modri enotirni vlak', category: 'transport', image: './assets/transport/white-blue-elevated-monorail.jpg' },
    { id: 'transport-red-snowmobile', name: 'Rdeče motorne sani', category: 'transport', image: './assets/transport/red-snowmobile.jpg' },
    { id: 'transport-green-farm-tractor', name: 'Zeleni traktor', category: 'transport', image: './assets/transport/green-farm-tractor.jpg' },
    { id: 'transport-yellow-cycle-rickshaw', name: 'Rumena kolesarska rikša', category: 'transport', image: './assets/transport/yellow-cycle-rickshaw.jpg' },
    { id: 'transport-red-alpine-cable-car-gondola', name: 'Rdeča kabinska žičnica', category: 'transport', image: './assets/transport/red-alpine-cable-car-gondola.jpg' },
    { id: 'transport-purple-tuk-tuk', name: 'Vijolični tuk-tuk', category: 'transport', image: './assets/transport/purple-tuk-tuk.jpg' },
    { id: 'transport-dark-blue-cargo-bicycle', name: 'Temnomodro tovorno kolo', category: 'transport', image: './assets/transport/dark-blue-cargo-bicycle.jpg' },
    { id: 'transport-bright-red-skateboard', name: 'Rdeča rolka', category: 'transport', image: './assets/transport/bright-red-skateboard.jpg' },
    { id: 'transport-silver-electric-unicycle', name: 'Srebrno električno enokolo', category: 'transport', image: './assets/transport/silver-electric-unicycle.jpg' },
    { id: 'transport-orange-tracked-excavator', name: 'Oranžni bager', category: 'transport', image: './assets/transport/orange-tracked-excavator.jpg' },
    { id: 'object-cobalt-blue-ceramic-mug', name: 'Modra keramična skodelica', category: 'objects', image: './assets/objects/cobalt-blue-ceramic-mug.jpg' },
    { id: 'object-red-twin-bell-alarm-clock', name: 'Rdeča budilka', category: 'objects', image: './assets/objects/red-twin-bell-alarm-clock.jpg' },
    { id: 'object-yellow-closed-umbrella', name: 'Rumeni dežnik', category: 'objects', image: './assets/objects/yellow-closed-umbrella.jpg' },
    { id: 'object-mint-green-instant-camera', name: 'Mintno zeleni fotoaparat', category: 'objects', image: './assets/objects/mint-green-instant-camera.jpg' },
    { id: 'object-ornate-brass-house-key', name: 'Medeninasti ključ', category: 'objects', image: './assets/objects/ornate-brass-house-key.jpg' },
    { id: 'object-teal-handled-scissors', name: 'Turkizne škarje', category: 'objects', image: './assets/objects/teal-handled-scissors.jpg' },
    { id: 'object-orange-stovetop-kettle', name: 'Oranžni čajnik', category: 'objects', image: './assets/objects/orange-stovetop-kettle.jpg' },
    { id: 'object-purple-hardcover-book', name: 'Vijolična knjiga', category: 'objects', image: './assets/objects/purple-hardcover-book.jpg' },
    { id: 'object-bright-green-sneaker', name: 'Zelena superga', category: 'objects', image: './assets/objects/bright-green-sneaker.jpg' },
    { id: 'object-cream-over-ear-headphones', name: 'Kremne slušalke', category: 'objects', image: './assets/objects/cream-over-ear-headphones.jpg' },
    { id: 'object-wooden-handle-claw-hammer', name: 'Kladivo z lesenim ročajem', category: 'objects', image: './assets/objects/wooden-handle-claw-hammer.jpg' },
    { id: 'object-teal-anglepoise-desk-lamp', name: 'Turkizna namizna svetilka', category: 'objects', image: './assets/objects/teal-anglepoise-desk-lamp.jpg' },
    { id: 'object-red-two-slot-toaster', name: 'Rdeči opekač', category: 'objects', image: './assets/objects/red-two-slot-toaster.jpg' },
    { id: 'object-green-metal-watering-can', name: 'Zelena zalivalka', category: 'objects', image: './assets/objects/green-metal-watering-can.jpg' },
    { id: 'object-silver-soup-spoon', name: 'Srebrna žlica', category: 'objects', image: './assets/objects/silver-soup-spoon.jpg' },
    { id: 'object-blue-manual-toothbrush', name: 'Modra zobna ščetka', category: 'objects', image: './assets/objects/blue-manual-toothbrush.jpg' },
    { id: 'object-red-round-eyeglasses', name: 'Rdeča očala', category: 'objects', image: './assets/objects/red-round-eyeglasses.jpg' },
    { id: 'object-wide-tooth-wooden-comb', name: 'Leseni glavnik', category: 'objects', image: './assets/objects/wide-tooth-wooden-comb.jpg' },
    { id: 'object-yellow-handheld-flashlight', name: 'Rumena ročna svetilka', category: 'objects', image: './assets/objects/yellow-handheld-flashlight.jpg' },
    { id: 'object-sunny-yellow-day-backpack', name: 'Rumeni nahrbtnik', category: 'objects', image: './assets/objects/sunny-yellow-day-backpack.jpg' },
    { id: 'landscape-slovenian-alpine-valley', name: 'Slovenska alpska dolina', category: 'landscapes', image: './assets/landscapes/slovenian-alpine-valley.jpg' },
    { id: 'landscape-golden-desert-dunes', name: 'Zlate puščavske sipine', category: 'landscapes', image: './assets/landscapes/golden-desert-dunes.jpg' },
    { id: 'landscape-tropical-white-sand-beach', name: 'Tropska peščena plaža', category: 'landscapes', image: './assets/landscapes/tropical-white-sand-beach.jpg' },
    { id: 'landscape-forest-waterfall-emerald-pool', name: 'Gozdni slap', category: 'landscapes', image: './assets/landscapes/forest-waterfall-emerald-pool.jpg' },
    { id: 'landscape-purple-lavender-fields', name: 'Polja sivke', category: 'landscapes', image: './assets/landscapes/purple-lavender-fields.jpg' },
    { id: 'landscape-glowing-autumn-beech-forest', name: 'Jesenski bukov gozd', category: 'landscapes', image: './assets/landscapes/glowing-autumn-beech-forest.jpg' },
    { id: 'landscape-blue-white-glacier', name: 'Modro-beli ledenik', category: 'landscapes', image: './assets/landscapes/blue-white-glacier.jpg' },
    { id: 'landscape-red-rock-river-canyon', name: 'Kanjon z reko', category: 'landscapes', image: './assets/landscapes/red-rock-river-canyon.jpg' },
    { id: 'landscape-green-terraced-rice-fields', name: 'Zelene riževe terase', category: 'landscapes', image: './assets/landscapes/green-terraced-rice-fields.jpg' },
    { id: 'landscape-black-volcanic-lava-island', name: 'Vulkanski otok', category: 'landscapes', image: './assets/landscapes/black-volcanic-lava-island.jpg' },
    { id: 'landscape-arctic-tundra-aurora', name: 'Arktična tundra s polarnim sijem', category: 'landscapes', image: './assets/landscapes/arctic-tundra-aurora.jpg' },
    { id: 'landscape-golden-savanna-acacia', name: 'Zlata savana', category: 'landscapes', image: './assets/landscapes/golden-savanna-acacia.jpg' },
    { id: 'landscape-misty-wetland-marsh', name: 'Megleno mokrišče', category: 'landscapes', image: './assets/landscapes/misty-wetland-marsh.jpg' },
    { id: 'landscape-white-sea-cliffs', name: 'Bele morske pečine', category: 'landscapes', image: './assets/landscapes/white-sea-cliffs.jpg' },
    { id: 'landscape-pink-flowering-spring-valley', name: 'Cvetoča pomladna dolina', category: 'landscapes', image: './assets/landscapes/pink-flowering-spring-valley.jpg' },
    { id: 'landscape-reflective-white-salt-flat', name: 'Odsevno slano jezero', category: 'landscapes', image: './assets/landscapes/reflective-white-salt-flat.jpg' },
    { id: 'landscape-rolling-golden-wheat-fields', name: 'Valovita pšenična polja', category: 'landscapes', image: './assets/landscapes/rolling-golden-wheat-fields.jpg' },
    { id: 'landscape-green-mangrove-lagoon', name: 'Mangrovska laguna', category: 'landscapes', image: './assets/landscapes/green-mangrove-lagoon.jpg' },
    { id: 'landscape-deep-blue-mountain-fjord', name: 'Globoki gorski fjord', category: 'landscapes', image: './assets/landscapes/deep-blue-mountain-fjord.jpg' },
    { id: 'landscape-limestone-cave-turquoise-pool', name: 'Kraška jama', category: 'landscapes', image: './assets/landscapes/limestone-cave-turquoise-pool.jpg' },
    { id: 'city-ljubljana-riverfront-castle', name: 'Ljubljana', category: 'cities', image: './assets/cities/ljubljana-riverfront-castle.jpg' },
    { id: 'city-venice-turquoise-canal', name: 'Benetke', category: 'cities', image: './assets/cities/venice-turquoise-canal.jpg' },
    { id: 'city-new-york-manhattan-skyline', name: 'New York', category: 'cities', image: './assets/cities/new-york-manhattan-skyline.jpg' },
    { id: 'city-tokyo-modern-crossing', name: 'Tokio', category: 'cities', image: './assets/cities/tokyo-modern-crossing.jpg' },
    { id: 'city-paris-seine-eiffel-tower', name: 'Pariz', category: 'cities', image: './assets/cities/paris-seine-eiffel-tower.jpg' },
    { id: 'city-london-thames-westminster', name: 'London', category: 'cities', image: './assets/cities/london-thames-westminster.jpg' },
    { id: 'city-istanbul-bosphorus-domes', name: 'Istanbul', category: 'cities', image: './assets/cities/istanbul-bosphorus-domes.jpg' },
    { id: 'city-sydney-opera-harbor', name: 'Sydney', category: 'cities', image: './assets/cities/sydney-opera-harbor.jpg' },
    { id: 'city-rio-coastline-mountains', name: 'Rio de Janeiro', category: 'cities', image: './assets/cities/rio-coastline-mountains.jpg' },
    { id: 'city-amsterdam-tree-lined-canal', name: 'Amsterdam', category: 'cities', image: './assets/cities/amsterdam-tree-lined-canal.jpg' },
    { id: 'city-prague-charles-bridge', name: 'Praga', category: 'cities', image: './assets/cities/prague-charles-bridge.jpg' },
    { id: 'city-barcelona-basilica', name: 'Barcelona', category: 'cities', image: './assets/cities/barcelona-basilica-city.jpg' },
    { id: 'city-dubai-futuristic-skyline', name: 'Dubaj', category: 'cities', image: './assets/cities/dubai-futuristic-skyline.jpg' },
    { id: 'city-singapore-tropical-waterfront', name: 'Singapur', category: 'cities', image: './assets/cities/singapore-tropical-waterfront.jpg' },
    { id: 'city-cape-town-table-mountain', name: 'Cape Town', category: 'cities', image: './assets/cities/cape-town-table-mountain.jpg' },
    { id: 'city-rome-ancient-amphitheater', name: 'Rim', category: 'cities', image: './assets/cities/rome-ancient-amphitheater.jpg' },
    { id: 'city-athens-acropolis', name: 'Atene', category: 'cities', image: './assets/cities/athens-acropolis-city.jpg' },
    { id: 'city-cairo-nile-pyramids', name: 'Kairo', category: 'cities', image: './assets/cities/cairo-nile-pyramids.jpg' },
    { id: 'city-san-francisco-orange-bridge', name: 'San Francisco', category: 'cities', image: './assets/cities/san-francisco-orange-bridge.jpg' },
    { id: 'city-seoul-palace-modern-skyline', name: 'Seul', category: 'cities', image: './assets/cities/seoul-palace-modern-skyline.jpg' },
]);

export function resolvedMemoryCatalog() {
    return MEMORY_CATALOG.map(item => ({ ...item, url: new URL(item.image, import.meta.url).href }));
}
