// Generated by scripts/optimize-twisty-palette.mjs; no runtime optimization.
export const BRIGHT_PALETTE = {
  "config": {
    "count": 20,
    "channelStep": 8,
    "restarts": 24,
    "exchanges": 100,
    "seed": 73129
  },
  "space": "OKLab Euclidean",
  "constraint": "HSV value = 100%",
  "minimumDistance": 0.14175872820776966,
  "colours": [
    "#00ff00",
    "#0000ff",
    "#ff0030",
    "#a0c0ff",
    "#b808ff",
    "#ffffc8",
    "#ff30ff",
    "#ff98ff",
    "#2068ff",
    "#00f0ff",
    "#f8ff00",
    "#ffd8ff",
    "#ff58a8",
    "#b080ff",
    "#7000ff",
    "#ffa8a0",
    "#ff7800",
    "#88ffa8",
    "#30a0ff",
    "#ffc000"
  ]
};
